# Generated by Django 2.2.6 on 2019-11-26 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.file_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CATEGORY1', 'CATEGORY1'), ('CATEGORY2', 'CATEGORY2'), ('CATEGORY3', 'CATEGORY3')], default='CATEGORY1', max_length=100)),
                ('color', models.CharField(choices=[('RED', 'RED'), ('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('WHITE', 'WHITE')], default='BLACK', max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', validators=[utils.file_utils.validate_image_extension, utils.file_utils.validate_image_size])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Article')),
            ],
        ),
    ]
